#.bash_aliases
alias dir='ls'
alias copy='cp'
alias erase='rm'
alias md='mkdir'
alias rename='mv'
alias ren='mv'
alias cls='clear'
alias del='rm'
alias find='grep' 
alias move='mv'
alias print='cat'
alias rd='rm -r'
alias rmdir='rm -r'
alias tree='ls -LR'
alias chdir='cd'

